### ISSUE TITLE
Decrease time to start running

### ISSUE THREAD

**Issue by alexboden** [WATonomous/run-gha-on-slurm#8]
Once jobs are queued, it takes a few minutes for the actions runner container to boot up.

Potential solutions:
- Caching the docker image
- Always having some runners allocated (no scale to zero)
- Keep ephemeral runners online if there is another job 
  - not sure how the logic would work, seems messy

**Comment by ben-z** [comment]
Would be nice to have a profile to see which step is taking a lot of time.

> Keep ephemeral runners online if there is another job

Yea I agree this sounds messy.

> Caching the docker image

Yea this could work, worst case we `docker save` and `docker load` from wato-drive*.

> Always having some runners allocated (no scale to zero)

Seems cleaner to have scale to zero.
